
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsdb
  password: <%= ENV['RAILSDB_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: econo_sim_development

test:
  <<: *default
  host: localhost
  database: econo_sim_test

production:
  <<: *default

  database: econo_sim_production